# -*- coding: utf-8 -*-
"""hangman resue

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d4iOYsZqRVDvgI8CK1xmKJqy16zWf6M4
"""

import random

# Step 1: List of possible secret words
words = ["dragon", "wizard", "castle", "magic", "sword", "kingdom"]

# Step 2: Choose a random word
secret_word = random.choice(words)
guessed_letters = []
incorrect_guesses = 0
max_incorrect = 6  # The prisoner has 6 chances

# Step 3: Display welcome message
print("🧙‍♂️ Welcome to the Magical Word Rescue!")
print(f"You have {max_incorrect} chances to guess the secret word and save the prisoner!")

# Step 4: Game loop
while True:
    # Display the word with underscores for unguessed letters
    display_word = ""
    for letter in secret_word:
        if letter in guessed_letters:
            display_word += letter + " "
        else:
            display_word += "_ "
    print("\nWord:", display_word.strip())

    # Check if the player has guessed all letters
    if "_" not in display_word:
        print("🎉 Congratulations! You saved the prisoner!")
        break

    # Ask the player for a guess
    guess = input("Guess a letter: ").lower()

    # Validate input
    if len(guess) != 1 or not guess.isalpha():
        print("❌ Please enter a single letter.")
        continue

    # Check if letter was already guessed
    if guess in guessed_letters:
        print("⚠️ You already guessed that letter.")
        continue

    guessed_letters.append(guess)

    # Check if guess is in the secret word
    if guess in secret_word:
        print("✅ Correct!")
    else:
        print("❌ Wrong!")
        incorrect_guesses += 1
        print(f"Remaining chances: {max_incorrect - incorrect_guesses}")

    # Check if max incorrect guesses reached
    if incorrect_guesses >= max_incorrect:
        print(f"💀 Game Over! The prisoner was doomed. The word was '{secret_word}'.")
        break



